[package]
name = "patch"
version = "1.0.0"
edition = "2021"

[lib]
crate-type = ["dylib"]

[dependencies]
ilhook = "2.0.0"
object = "0.32.1"
region = "3.0.0"
wchar = "0.11.0"
winapi = { version = "0.3.9", features = ["libloaderapi", "minwindef", "winnt"] }
