[package]
name = "patch"
version = "1.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
bitflags = "2.4.1"
ilhook = "2.0.0"
mlua = { version = "0.9.1", features = ["lua54", "module"] }
